export const ADD_TO_CART = "ADD_TO_CART";
export const INC_CART_ITEM_QUANTITY = "INC_CART_ITEM_QUANTITY";
export const DEC_CART_ITEM_QUANTITY = "DEC_CART_ITEM_QUANTITY";
export const DELETE_ITEM_FROM_CART = "DELETE_ITEM_FROM_CART";
export const DEC_SHOP_ITEM_QTY = "DEC_SHOP_ITEM_QTY";
